### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by amueller** [amueller/futurepast#1]
Renaming:
- [x] Rename function
- [x] Rename classes
- [ ] Rename methods
- [ ] Rename modules
- [ ] Rename constants
- [ ] Rename attributes

Removing:
- [x] Remove functions
- [x] Remove classes
- [ ] Remove methods
- [ ] Remove modules
- [ ] Remove constants
- [ ] Remove attributes

Parameters:
- [x] Rename parameter
- [x] Remove parameter
- [x] Change default value
- [ ] Docstrings for rename
- [ ] Docstrings for remove
- [ ] Docstrings for change default

Versions:
- [ ] Check if version is between past and future
- [ ] raise appropriate errors in the future

Moving to a different module?

**Comment by cavaunpeu** [comment]
👍
